# vim:ft=kitty

## name: Nightcity
## author: NXTaar
## license: MIT

# Border
active_border_color #719cd6
inactive_border_color #39506d
bell_border_color #f4a261

# Tabs
active_tab_background #719cd6
active_tab_foreground #131a24
inactive_tab_background #2b3b51
inactive_tab_foreground #738091

foreground            #D8DEE9
background            #191b29
selection_foreground  #000000
selection_background  #2a2c35
url_color             #0087BD
cursor                #81A1C1

# black
color0   #14151f
color8   #14151f

# red
color1   #ff5f3b
color9   #f76f63

# green
color2   #9ea32a
color10  #a3a559

# yellow
color3   #ffb833
color11  #f6c55b

# blue
color4  #6e9685
color12 #919c96

# magenta
color5   #db5b8a
color13  #d87e9e

# cyan
color6   #67c4bd
color14  #89c5bf

# white
color7   #fbf1c7
color15  #fbf1c7

# extended colors
color16 #f4a261
color17 #d67ad2