---
# - ansible.builtin.import_tasks: ubuntu.yaml
  # when: ansible_host_environment_is_wsl

- name: LAZYGIT | Install
  become: true
  when: ansible_host_environment_is_wsl
  ansible.builtin.shell: |
    LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
    tar xf lazygit.tar.gz lazygit
    sudo install lazygit /usr/local/bin
    rm -rf lazygit lazygit.tar.gz
  args:
    executable: /bin/bash

