---
- ansible.builtin.import_tasks: ubuntu.yaml
  when: ansible_host_environment_is_wsl

- name: NVIM | Install additional tools
  community.general.cargo:
    name:
     - tree-sitter-cli
     - ripgrep
    state: latest
  tags:
    - cargo

- name: NVIM | Link configuration files
  ansible.builtin.file:
    src: "{{ ansible_dotfiles_root }}/nvim"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: true

