---
- name: NVIM | Install (Ubuntu | WSL)
  become: true
  tags:
   - install
   - nvim
  block:
    - name: NVIM | Download and install NVIM archive
      ansible.builtin.shell: |
        curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        rm -rf /opt/nvim
        tar -C /opt -xzf nvim-linux64.tar.gz --transform 's/-linux64//'
      args:
        executable: /bin/bash
        chdir: /tmp
