---
- block:
  - name: Resolve dotfiles repo root
    ansible.builtin.shell: >
      cd "$(dirname "${BASH_SOURCE[0]}")" || exit ; pwd -P | sed -r 's/(.+dotfiles).+/\1/g'
    args:
      executable: /bin/bash
    register: ansible_dotfiles_root_folder_shell
    ignore_errors: true

  - name: "Setting Dotfiles root variable"
    ansible.builtin.set_fact:
      ansible_dotfiles_root: "{{ ansible_dotfiles_root_folder_shell.stdout | default('') }}"

  - name: Show dotfiles repo root
    ansible.builtin.debug:
      msg: "Dotfiles Repo: {{ ansible_dotfiles_root }}"

  - name: Create root file for use in configs
    copy:
        dest: "{{ ansible_env.HOME }}/.dotfilesrc"
        content: |
          export DOTFILES_ROOT_FOLDER={{ ansible_dotfiles_root }}
  tags:
  - always

