ENCODER_MAP_ENABLE = yes
CONSOLE_ENABLE = yes
OS_DETECTION_ENABLE = yes
OS_DETECTION_DEBUG_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_DRIVER = ws2812
