console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
grey = '#6c6c6c'

[secondary_prompt]
template = '󰅂󰅂 '
foreground = 'green'
background = 'transparent'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = '{{ .Path }}'
foreground = 'blue'
background = 'transparent'
type = 'path'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'agnoster_full'

[[blocks.segments]]
template = ' 󰅂'
background = 'transparent'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}green{{end}}',
]

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if and .UpstreamURL (or (gt .Behind 0) (gt .Ahead 0)) }} <cyan>{{ if gt .Behind 0 }}↓{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }}↑{{ .Ahead }}{{ end }}</cyan>{{ end }}'
foreground = 'p:grey'
background = 'transparent'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ' '
cache_duration = 'none'
commit_icon = ''
fetch_status = true

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }} '
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 1000
