---
- name: NXTaar Dev Environment
  hosts: localhost
  connection: local

  pre_tasks:
  - import_tasks: pre_tasks/detect_wsl.yaml
  - import_tasks: pre_tasks/dotfiles_root.yaml

  roles:
    - rust
    - zsh
    - lazygit
    - nvim
    - wezterm
    - node
